name: Run Script for EU Data

on:
  # schedule:
  #   - cron: "30 5 * * 2"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          DATADUMP_PREFIX: ${{ secrets.DATADUMP_PREFIX }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          UPDATE_PG_DATABASE: ${{ vars.UPDATE_PG_DATABASE }}
          LANDINGAI_API_KEY: ${{ secrets.LANDINGAI_API_KEY }}
          AUTOMATED_UPLOAD_PREFIX: ${{ secrets.AUTOMATED_UPLOAD_PREFIX }}
          EU_AUTOMATED_RUN: ${{ vars.EU_AUTOMATED_RUN }}
          PREFIX: ${{ secrets.PREFIX }}
        run: python src/eu_data.py